apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: todo-backend
spec:
  type: LoadBalancer 
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
